//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Survey.Model.Query
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Sheelon
    {
        public int Id { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string name { get; set; }
        public Nullable<bool> shared { get; set; }
        public string F1 { get; set; }
        public string F2 { get; set; }
        public string F3 { get; set; }
    }
}
